version: "3"
services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: ${VITE_DB_USER}
      POSTGRES_PASSWORD: ${VITE_DB_PASSWORD}
      POSTGRES_DB: ${VITE_DB_NAME}
    ports:
      - "${VITE_DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
